---
metadata:
  source: HESA
  name: degree_type
  display_name: Degree type
  description: ''
  change_log:
  - date: '2025-11-19'
    change: Initial version
    author: Register team
data:
- id: c1695652-c197-e711-80d8-005056ac45bb
  name: bed
  display_name: BEd
  hesa_codes:
  - '001'
- id: c5695652-c197-e711-80d8-005056ac45bb
  name: bsc_education
  display_name: BSc/Education
  hesa_codes:
  - '003'
- id: c9695652-c197-e711-80d8-005056ac45bb
  name: btech_education
  display_name: BTech/Education
  hesa_codes:
  - '005'
- id: cd695652-c197-e711-80d8-005056ac45bb
  name: ba_education
  display_name: BA/Education
  hesa_codes:
  - '007'
- id: d1695652-c197-e711-80d8-005056ac45bb
  name: ba_combined_studies_education_of_the_deaf
  display_name: BA Combined Studies/Education of the Deaf
  hesa_codes:
  - '009'
- id: d5695652-c197-e711-80d8-005056ac45bb
  name: ba_with_intercalated_pgce
  display_name: BA with intercalated PGCE
  hesa_codes:
  - '012'
- id: db695652-c197-e711-80d8-005056ac45bb
  name: ba
  display_name: Bachelor of Arts
  hesa_codes:
  - '051'
- id: dd695652-c197-e711-80d8-005056ac45bb
  name: baecon
  display_name: Bachelor of Arts Economics
  hesa_codes:
  - '052'
- id: df695652-c197-e711-80d8-005056ac45bb
  name: baarch
  display_name: Bachelor of Arts in Architecture
  hesa_codes:
  - '053'
- id: e1695652-c197-e711-80d8-005056ac45bb
  name: bao
  display_name: Bachelor of the Art of Obstetrics
  hesa_codes:
  - '054'
- id: e3695652-c197-e711-80d8-005056ac45bb
  name: baarch
  display_name: Bachelor of Architecture
  hesa_codes:
  - '055'
- id: e5695652-c197-e711-80d8-005056ac45bb
  name: basc
  display_name: Bachelor of Applied Science
  hesa_codes:
  - '056'
- id: e7695652-c197-e711-80d8-005056ac45bb
  name: bag
  display_name: Bachelor of Agriculture
  hesa_codes:
  - '057'
- id: e9695652-c197-e711-80d8-005056ac45bb
  name: bacc
  display_name: Bachelor of Accountancy
  hesa_codes:
  - '058'
- id: eb695652-c197-e711-80d8-005056ac45bb
  name: badmin
  display_name: Bachelor of Administration
  hesa_codes:
  - '059'
- id: ed695652-c197-e711-80d8-005056ac45bb
  name: bba
  display_name: Bachelor of Business Administration
  hesa_codes:
  - '060'
- id: ef695652-c197-e711-80d8-005056ac45bb
  name: bcs
  display_name: Bachelor of Combined Studies
  hesa_codes:
  - '061'
- id: f1695652-c197-e711-80d8-005056ac45bb
  name: bcomm
  display_name: Bachelor of Commerce
  hesa_codes:
  - '062'
- id: f3695652-c197-e711-80d8-005056ac45bb
  name: bd
  display_name: Bachelor of Divinity
  hesa_codes:
  - '063'
- id: f5695652-c197-e711-80d8-005056ac45bb
  name: bds
  display_name: Bachelor of Dental Surgery
  hesa_codes:
  - '064'
- id: f7695652-c197-e711-80d8-005056ac45bb
  name: beng
  display_name: Bachelor of Engineering
  hesa_codes:
  - '065'
- id: f9695652-c197-e711-80d8-005056ac45bb
  name: beng/bs
  display_name: Bachelor of Engineering with Business Studies
  hesa_codes:
  - '066'
- id: fb695652-c197-e711-80d8-005056ac45bb
  name: bfa
  display_name: Bachelor of Fine Art
  hesa_codes:
  - '067'
- id: fd695652-c197-e711-80d8-005056ac45bb
  name: bgs
  display_name: Bachelor of General Studies
  hesa_codes:
  - '068'
- id: ff695652-c197-e711-80d8-005056ac45bb
  name: bh
  display_name: Bachelor of Humanities
  hesa_codes:
  - '069'
- id: 016a5652-c197-e711-80d8-005056ac45bb
  name: bhyg
  display_name: Bachelor of Hygiene
  hesa_codes:
  - '070'
- id: 036a5652-c197-e711-80d8-005056ac45bb
  name: llb
  display_name: Bachelor of Law
  hesa_codes:
  - '071'
- id: 056a5652-c197-e711-80d8-005056ac45bb
  name: blib
  display_name: Bachelor of Librarianship
  hesa_codes:
  - '072'
- id: 076a5652-c197-e711-80d8-005056ac45bb
  name: bls
  display_name: Bachelor of Librarianship and Information Studies
  hesa_codes:
  - '073'
- id: '096a5652-c197-e711-80d8-005056ac45bb'
  name: blitt
  display_name: Bachelor of Literature
  hesa_codes:
  - '074'
- id: 0b6a5652-c197-e711-80d8-005056ac45bb
  name: blecon
  display_name: Bachelor of Land Economy
  hesa_codes:
  - '075'
- id: 0d6a5652-c197-e711-80d8-005056ac45bb
  name: bmedsc
  display_name: Bachelor of Medical Science
  hesa_codes:
  - '076'
- id: 0f6a5652-c197-e711-80d8-005056ac45bb
  name: bm
  display_name: Bachelor of Medicine
  hesa_codes:
  - '077'
- id: 116a5652-c197-e711-80d8-005056ac45bb
  name: bmet
  display_name: Bachelor of Metallurgy
  hesa_codes:
  - '078'
- id: 136a5652-c197-e711-80d8-005056ac45bb
  name: bmet/eng
  display_name: Bachelor of Metallurgy and Engineering
  hesa_codes:
  - '079'
- id: 156a5652-c197-e711-80d8-005056ac45bb
  name: bmus
  display_name: Bachelor of Music
  hesa_codes:
  - '080'
- id: 176a5652-c197-e711-80d8-005056ac45bb
  name: bn
  display_name: Bachelor of Nursing
  hesa_codes:
  - '081'
- id: 196a5652-c197-e711-80d8-005056ac45bb
  name: bpharm
  display_name: Bachelor of Pharmacy
  hesa_codes:
  - '082'
- id: 1b6a5652-c197-e711-80d8-005056ac45bb
  name: bsc
  display_name: Bachelor of Science
  hesa_codes:
  - '083'
- id: 1d6a5652-c197-e711-80d8-005056ac45bb
  name: bscecon
  display_name: Bachelor of Science Economics
  hesa_codes:
  - '084'
- id: 1f6a5652-c197-e711-80d8-005056ac45bb
  name: bsceng
  display_name: Bachelor of Science and Engineering
  hesa_codes:
  - '085'
- id: 216a5652-c197-e711-80d8-005056ac45bb
  name: bsctech
  display_name: Bachelor of Science and Technology
  hesa_codes:
  - '086'
- id: 236a5652-c197-e711-80d8-005056ac45bb
  name: bsc ss
  display_name: Bachelor of Science in Social Science
  hesa_codes:
  - '087'
- id: 256a5652-c197-e711-80d8-005056ac45bb
  name: bsc spt
  display_name: Bachelor of Science in Speech Therapy
  hesa_codes:
  - '088'
- id: 276a5652-c197-e711-80d8-005056ac45bb
  name: bss
  display_name: Bachelor of Social Science
  hesa_codes:
  - '089'
- id: 296a5652-c197-e711-80d8-005056ac45bb
  name: bs
  display_name: Bachelor of Surgery
  hesa_codes:
  - '090'
- id: 2b6a5652-c197-e711-80d8-005056ac45bb
  name: bch
  display_name: Bachelor of Chirurgiae
  hesa_codes:
  - '091'
- id: 2d6a5652-c197-e711-80d8-005056ac45bb
  name: btech
  display_name: Bachelor of Technology
  hesa_codes:
  - '092'
- id: 2f6a5652-c197-e711-80d8-005056ac45bb
  name: btheol
  display_name: Bachelor of Theology
  hesa_codes:
  - '093'
- id: 316a5652-c197-e711-80d8-005056ac45bb
  name: bvmed
  display_name: Bachelor of Veterinary Medicine
  hesa_codes:
  - '094'
- id: 336a5652-c197-e711-80d8-005056ac45bb
  name: bvms
  display_name: Bachelor of Veterinary Medicine and Surgery
  hesa_codes:
  - '095'
- id: 356a5652-c197-e711-80d8-005056ac45bb
  name: bvsc
  display_name: Bachelor of Veterinary Science
  hesa_codes:
  - '096'
- id: 376a5652-c197-e711-80d8-005056ac45bb
  name: bed
  display_name: Bachelor of Education Scotland and Northern Ireland
  hesa_codes:
  - '097'
- id: 396a5652-c197-e711-80d8-005056ac45bb
  name: bphil
  display_name: Bachelor of Philosophy
  hesa_codes:
  - '098'
- id: 3b6a5652-c197-e711-80d8-005056ac45bb
  name: ma
  display_name: Master of Arts
  hesa_codes:
  - '200'
- id: 3d6a5652-c197-e711-80d8-005056ac45bb
  name: mlib
  display_name: Master of Librarianship
  hesa_codes:
  - '201'
- id: 3f6a5652-c197-e711-80d8-005056ac45bb
  name: mlitt
  display_name: Master of Literature
  hesa_codes:
  - '202'
- id: 416a5652-c197-e711-80d8-005056ac45bb
  name: mmus
  display_name: Master of Music
  hesa_codes:
  - '203'
- id: 436a5652-c197-e711-80d8-005056ac45bb
  name: mphil
  display_name: Master of Philosophy
  hesa_codes:
  - '204'
- id: 456a5652-c197-e711-80d8-005056ac45bb
  name: msc
  display_name: Master of Science
  hesa_codes:
  - '205'
- id: 476a5652-c197-e711-80d8-005056ac45bb
  name: mtheol
  display_name: Master of Theology
  hesa_codes:
  - '206'
- id: 496a5652-c197-e711-80d8-005056ac45bb
  name: certificate_of_membership_of_cranfield_institute_of_technology
  display_name: Certificate of Membership of Cranfield Institute of Technology
  hesa_codes:
  - '207'
- id: 4b6a5652-c197-e711-80d8-005056ac45bb
  name: med
  display_name: Master of Education
  hesa_codes:
  - '208'
- id: 4d6a5652-c197-e711-80d8-005056ac45bb
  name: mbs
  display_name: Master of Business Studies
  hesa_codes:
  - '209'
- id: 4f6a5652-c197-e711-80d8-005056ac45bb
  name: mss
  display_name: Master of Social Studies
  hesa_codes:
  - '210'
- id: 516a5652-c197-e711-80d8-005056ac45bb
  name: meng
  display_name: Master of Engineering
  hesa_codes:
  - '211'
- id: 536a5652-c197-e711-80d8-005056ac45bb
  name: mlaw
  display_name: Master of Law
  hesa_codes:
  - '212'
- id: 556a5652-c197-e711-80d8-005056ac45bb
  name: mba
  display_name: Master of Business Administration
  hesa_codes:
  - '213'
- id: 576a5652-c197-e711-80d8-005056ac45bb
  name: mchem
  display_name: Master of Chemistry
  hesa_codes:
  - '214'
- id: 596a5652-c197-e711-80d8-005056ac45bb
  name: mphys
  display_name: Master of Physics
  hesa_codes:
  - '215'
- id: 5b6a5652-c197-e711-80d8-005056ac45bb
  name: dd
  display_name: Doctor of Divinity
  hesa_codes:
  - '300'
- id: 5d6a5652-c197-e711-80d8-005056ac45bb
  name: dcl
  display_name: Doctor of Civil Law
  hesa_codes:
  - '301'
- id: 5f6a5652-c197-e711-80d8-005056ac45bb
  name: md
  display_name: Doctor of Medicine
  hesa_codes:
  - '302'
- id: 616a5652-c197-e711-80d8-005056ac45bb
  name: dmu
  display_name: Doctor of Music
  hesa_codes:
  - '303'
- id: 636a5652-c197-e711-80d8-005056ac45bb
  name: dsc
  display_name: Doctor of Science
  hesa_codes:
  - '304'
- id: 656a5652-c197-e711-80d8-005056ac45bb
  name: dphil
  display_name: Doctor of Philosophy
  hesa_codes:
  - '305'
- id: 676a5652-c197-e711-80d8-005056ac45bb
  name: phd
  display_name: PhD
  hesa_codes:
  - '306'
- id: 696a5652-c197-e711-80d8-005056ac45bb
  name: first_degree
  display_name: First Degree
  hesa_codes:
  - '400'
- id: 6b6a5652-c197-e711-80d8-005056ac45bb
  name: higher_degree_or_equivalent
  display_name: Higher degree or equivalent
  hesa_codes:
  - '401'
- id: 6d6a5652-c197-e711-80d8-005056ac45bb
  name: degree_equivalent
  display_name: Degree equivalent
  hesa_codes:
  - '402'
- id: 6f6a5652-c197-e711-80d8-005056ac45bb
  name: unknown
  display_name: Unknown
  hesa_codes:
  - '999'
