metadata:
  source: "HESA"
  name: "trainee_study_mode"
  display_name: "Trainee study mode"
  change_log:                             # is this duplicating what's already in source control or do we need user facing changes like this?
    - date: "2025-11-19"                  # (probably only useful here if we can use them to automatically generate a reference data change log, assuming the reference data as a whole has a version number)
      change: "Initial version"           #
      author: "Register team"             #

data:
  - id: 0
    name: "part_time"
    display_name: "Part-time"             # should these be in an i18n file?
    description: "Part-time trainee"      #
    hesa_codes:
      - "31"
      - "64"
  - id: 1
    name: "full_time"
    display_name: "Full-time"
    description: "Full-time trainee"
    hesa_codes:
      - "01"
      - "02"
      - "63"
