metadata:
  source: "HESA"
  name: "training_route"
  display_name: "Training route"
  change_log:
    - date: "2025-11-26"
      change: "Initial version"
      author: "Register team"

data:
  - id: 0
    name: "assessment_only"
    display_name: "Assessment only"
    description: "Assessment only"
    hesa_codes:
  - id: 1
    name: "provider_led_postgrad"
    display_name: "Primary and Secondary Postgraduate Fee Funded"
    description: "Primary and Secondary Postgraduate Fee Funded"
    start_year: 2024
    hesa_codes:
      - "12"
  - id: 2
    name: "early_years_undergrad"
    display_name: "Early-years undergrad"
    description: "Early-years undergrad"
    hesa_codes:
  - id: 3
    name: "school_direct_tuition_fee"
    display_name: "School Direct tuition fee"
    description: "School Direct tuition fee"
    hesa_codes:
      - "02"
  - id: 4
    name: "school_direct_salaried"
    display_name: "School Direct salaried"
    description: "School Direct salaried"
    hesa_codes:
      - "03"
  - id: 5
    name: "pg_teaching_apprenticeship"
    display_name: "Postgraduate teaching apprenticeship"
    description: "Postgraduate teaching apprenticeship"
    hesa_codes:
      - "10"
  - id: 6
    name: "early_years_assessment_only"
    display_name: "Early years assessment only"
    description: "Early years assessment only"
    hesa_codes:
  - id: 7
    name: "early_years_salaried"
    display_name: "Early years salaried"
    description: "Early years salaried"
    hesa_codes:
  - id: 8
    name: "early_years_postgrad"
    display_name: "Early years postgrad"
    description: "Early years postgrad"
    hesa_codes:
  - id: 9
    name: "provider_led_undergrad"
    display_name: "Primary and Secondary Undergraduate Fee Funded"
    description: "Primary and Secondary Undergraduate Fee Funded"
    hesa_codes:
      - "11"
  - id: 10
    name: "opt_in_undergrad"
    display_name: "Undergraduate Opt-in"
    description: "Undergraduate Opt-in"
    hesa_codes:
      - "09"
  - id: 11
    name: "hpitt_postgrad"
    display_name: "HPITT postgrad"
    description: "HPITT postgrad"
    hesa_codes:
  - id: 12
    name: "iqts"
    display_name: "iQTS"
    description: "iQTS"
    hesa_codes:
  - id: 14
    name: "teacher_degree_apprenticeship"
    display_name: "Teacher Degree Apprenticeship"
    description: "Teacher Degree Apprenticeship"
    hesa_codes:
      - "14"
