shared:
  new_groups:
    - email
  new_partner_users:
    - email
  trainees:
    - first_names
    - last_name
    - email
    - date_of_birth
    - trn
  trainee_withdrawals:
    - safeguarding_concern_reasons
  users:
    - dfe_sign_in_uid
    - email
    - first_name
    - last_name
