shared:
  academic_cycles:
    - created_at
    - end_date
    - id
    - start_date
    - updated_at
  activities:
    - action_name
    - controller_name
    - created_at
    - id
    - metadata
    - updated_at
    - user_id
  allocation_subjects:
    - created_at
    - id
    - name
    - updated_at
  apply_applications:
    - accredited_body_code
    - apply_id
    - created_at
    - id
    - recruitment_cycle_year
    - state
    - updated_at
  bulk_update_row_errors:
    - id
    - created_at
    - updated_at
    - errored_on_id
    - errored_on_type
    - error_type
    - message
    - error_type
  bulk_update_trainee_uploads:
    - id
    - provider_id
    - status
    - created_at
    - updated_at
    - submitted_at
    - submitted_by_id
    - number_of_trainees
    - version
  course_subjects:
    - id
    - course_id
    - subject_id
    - created_at
    - updated_at
  courses:
    - accredited_body_code
    - code
    - course_length
    - created_at
    - duration_in_years
    - full_time_end_date
    - full_time_start_date
    - id
    - level
    - max_age
    - min_age
    - name
    - part_time_end_date
    - part_time_start_date
    - published_start_date
    - qualification
    - recruitment_cycle_year
    - route
    - study_mode
    - summary
    - updated_at
    - uuid
  degrees:
    - country
    - created_at
    - dttp_id
    - grade
    - grade_uuid
    - graduation_year
    - id
    - institution
    - institution_uuid
    - locale_code
    - non_uk_degree
    - other_grade
    - slug
    - subject
    - subject_uuid
    - trainee_id
    - uk_degree
    - uk_degree_uuid
    - updated_at
  disabilities:
    - created_at
    - id
    - updated_at
  dttp_providers:
    - created_at
    - dttp_id
    - id
    - name
    - ukprn
    - updated_at
  dttp_schools:
    - created_at
    - dttp_id
    - id
    - name
    - status_code
    - updated_at
    - urn
  funding_method_subjects:
    - allocation_subject_id
    - created_at
    - funding_method_id
    - id
    - updated_at
  funding_methods:
    - academic_cycle_id
    - amount
    - created_at
    - created_at
    - funding_type
    - id
    - training_route
    - updated_at
    - updated_at
  hesa_metadata:
    - course_programme_title
    - created_at
    - fundability
    - id
    - itt_aim
    - itt_qualification_aim
    - pg_apprenticeship_start_date
    - placement_school_urn
    - service_leaver
    - study_length
    - study_length_unit
    - trainee_id
    - updated_at
    - year_of_course
  hesa_trn_submissions:
    - id
    - created_at
    - submitted_at
    - updated_at
  training_partner_users:
    - id
    - training_partner_id
    - user_id
    - created_at
    - updated_at
  training_partners:
    - id
    - urn
    - record_type
    - name
    - ukprn
    - school_id
    - provider_id
    - created_at
    - updated_at
    - discarded_at
  nationalities:
    - created_at
    - id
    - name
    - updated_at
  nationalisations:
    - created_at
    - id
    - nationality_id
    - trainee_id
    - updated_at
  placements:
    - id
    - trainee_id
    - school_id
    - urn
    - name
    - address
    - postcode
    - created_at
    - updated_at
    - slug
  potential_duplicate_trainees:
    - id
    - group_id
    - trainee_id
    - created_at
    - updated_at
  provider_users:
    - created_at
    - id
    - provider_id
    - updated_at
    - user_id
  providers:
    - accreditation_id
    - apply_sync_enabled
    - code
    - created_at
    - dttp_id
    - id
    - name
    - ukprn
    - accredited
    - updated_at
    - discarded_at
  schools:
    - close_date
    - created_at
    - id
    - name
    - open_date
    - postcode
    - town
    - updated_at
    - urn
  sign_offs:
    - id
    - provider_id
    - academic_cycle_id
    - user_id
    - sign_off_type
    - created_at
    - updated_at
  subject_specialisms:
    - allocation_subject_id
    - created_at
    - hecos_code
    - id
    - name
    - updated_at
  subjects:
    - code
    - created_at
    - id
    - name
    - updated_at
  trainee_withdrawal_reasons:
    - id
    - trainee_id
    - withdrawal_reason_id
    - trainee_withdrawal_id
    - created_at
    - updated_at
  trainee_withdrawals:
    - id
    - trainee_id
    - date
    - trigger
    - another_reason
    - safeguarding_concern_reasons
    - future_interest
    - discarded_at
    - created_at
    - updated_at
  trainees:
    - apply_application_id
    - applying_for_bursary
    - applying_for_grant
    - applying_for_scholarship
    - awarded_at
    - bursary_tier
    - trainee_start_date
    - commencement_status
    - course_allocation_subject_id
    - course_education_phase
    - course_max_age
    - course_min_age
    - course_subject_one
    - course_subject_three
    - course_subject_two
    - course_uuid
    - created_at
    - created_from_dttp
    - created_from_hesa
    - date_of_birth
    - defer_date
    - defer_reason
    - disability_disclosure
    - discarded_at
    - diversity_disclosure
    - dormancy_dttp_id
    - dttp_id
    - dttp_update_sha
    - ebacc
    - email
    - employing_school_id
    - employing_school_not_applicable
    - end_academic_cycle_id
    - first_names
    - sex
    - hesa_id
    - hesa_updated_at
    - id
    - iqts_country
    - itt_end_date
    - itt_start_date
    - last_name
    - training_partner_id
    - placement_detail
    - training_partner_not_applicable
    - outcome_date
    - placement_assignment_dttp_id
    - progress
    - provider_id
    - recommended_for_award_at
    - record_source
    - region
    - reinstate_date
    - slug
    - start_academic_cycle_id
    - state
    - study_mode
    - submission_ready
    - submitted_for_trn_at
    - training_initiative
    - training_route
    - trn
    - updated_at
    - hesa_trn_submission_id
    - hesa_editable
    - slug_sent_to_dqt_at
    - application_choice_id
  trs_trn_requests:
    - id
    - trainee_id
    - request_id
    - response
    - state
    - created_at
    - updated_at
  users:
    - created_at
    - dfe_sign_in_uid
    - discarded_at
    - dttp_id
    - email
    - first_name
    - id
    - last_name
    - last_signed_in_at
    - system_admin
    - updated_at
    - welcome_email_sent_at
  withdrawal_reasons:
    - id
    - created_at
    - updated_at
    - name
