shared:
  activities:
    - action_name
    - controller_name
    - created_at
    - id
    - metadata
    - updated_at
    - user_id
  apply_applications:
    - accredited_body_code
    - apply_id
    - created_at
    - id
    - recruitment_cycle_year
    - state
    - updated_at
  allocation_subjects:
    - created_at
    - id
    - name
    - updated_at
  courses:
    - accredited_body_code
    - code
    - course_length
    - created_at
    - duration_in_years
    - full_time_end_date
    - full_time_start_date
    - id
    - level
    - max_age
    - min_age
    - name
    - part_time_end_date
    - part_time_start_date
    - published_start_date
    - qualification
    - recruitment_cycle_year
    - route
    - study_mode
    - summary
    - updated_at
    - uuid
  course_subjects:
    - id
    - course_id
    - subject_id
    - created_at
    - updated_at
  degrees:
    - country
    - created_at
    - dttp_id
    - grade
    - graduation_year
    - id
    - institution
    - locale_code
    - non_uk_degree
    - other_grade
    - slug
    - subject
    - trainee_id
    - uk_degree
    - updated_at
  dttp_providers:
    - created_at
    - dttp_id
    - id
    - name
    - ukprn
    - updated_at
  dttp_schools:
    - created_at
    - dttp_i
    - id
    - name
    - status_code
    - updated_at
    - urn
  funding_methods:
    - academic_cycle_id
    - allocation_subject_id
    - amount
    - bursary_id
    - created_at
    - created_at
    - funding_type
    - id
    - training_route
    - updated_at
    - updated_at
  funding_method_subjects:
    - allocation_subject_id
    - created_at
    - funding_method_id
    - id
    - updated_at
  nationalisations:
    - created_at
    - id
    - nationality_id
    - trainee_id
    - updated_at
  nationalities:
    - created_at
    - id
    - name
    - updated_at
  providers:
    - apply_sync_enabled
    - code
    - created_at
    - dttp_id
    - id
    - name
    - ukprn
    - updated_at
  schools:
    - close_date
    - created_at
    - created_at
    - data
    - id
    - id
    - lead_school
    - name
    - open_date
    - postcode
    - session_id
    - town
    - updated_at
    - updated_at
    - urn
  subject_specialisms:
    - allocation_subject_id
    - created_at
    - id
    - name
    - updated_at
  subjects:
    - code
    - created_at
    - id
    - name
    - updated_at
  trainees:
    - apply_application_id
    - applying_for_bursary
    - applying_for_grant
    - applying_for_scholarship
    - awarded_at
    - bursary_tier
    - commencement_date
    - commencement_status
    - course_education_phase
    - course_max_age
    - course_min_age
    - course_subject_one
    - course_subject_three
    - course_subject_two
    - course_uuid
    - created_at
    - defer_date
    - discarded_at
    - dormancy_dttp_id
    - dttp_id
    - dttp_update_sha
    - ebacc
    - employing_school_id
    - employing_school_not_applicable
    - gender
    - hesa_id
    - id
    - itt_end_date
    - itt_start_date
    - lead_school_id
    - lead_school_not_applicable
    - locale_code
    - outcome_date
    - placement_assignment_dttp_id
    - postcode
    - progress
    - provider_id
    - recommended_for_award_at
    - region
    - reinstate_date
    - slug
    - state
    - study_mode
    - submission_ready
    - submitted_for_trn_at
    - training_initiative
    - training_route
    - trn
    - updated_at
    - withdraw_date
    - withdraw_reason
  users:
    - created_at
    - dfe_sign_in_uid
    - discarded_at
    - dttp_id
    - id
    - last_signed_in_at
    - system_admin
    - updated_at
    - welcome_email_sent_at
  hesa_collection_requests:
    - requested_at
    - state
