---
# The authentication token for the application.
authentication: <%= Settings.skylight.authentication %>
ignored_endpoints:
  - HeartbeatController#ping
  - HeartbeatController#healthcheck
  - HeartbeatController#sha
