log_level: debug

dttp:
  api_base_url: "https://dttp-dev.api.crm4.dynamics.com"
  portal_host: traineeteacherportal-local.education.gov.uk

features:
  sign_in_method: persona # "dfe", "persona", "otp"
  basic_auth: false
  import_courses_from_ttapi: true
  publish_course_details: true
  funding: true

pagination:
  records_per_page: 30

environment:
  name: development
  display_name: Development

track_validation_errors: false

blazer_database_url: postgresql://localhost/register_trainee_teacher_data_development

api:
  allowed_versions: [v2025.0-rc, v2025.0, v2026.0]
