dttp:
  api_base_url: "https://dttp-dev.api.crm4.dynamics.com"

features:
  use_dfe_sign_in: false
  basic_auth: false
  import_courses_from_ttapi: true
  publish_course_details: true
  use_subject_specialisms_in_course_details: true
  routes:
    provider_led_postgrad: true
    early_years_assessment_only: true
    early_years_postgrad: true
    school_direct_salaried: true
    school_direct_tuition_fee: true

pagination:
  records_per_page: 30

environment:
  name: development

track_validation_errors: false
