dttp:
  api_base_url: "https://dttp-dev.api.crm4.dynamics.com"

features:
  use_dfe_sign_in: false
  basic_auth: false
  import_courses_from_ttapi: true
  publish_course_details: true
  enable_teach_first_provider: true
  course_study_mode: true
  scholarship: true
  routes:
    provider_led_postgrad: true
    early_years_assessment_only: true
    early_years_postgrad: true
    early_years_undergrad: true
    early_years_salaried: true
    school_direct_salaried: true
    school_direct_tuition_fee: true
    pg_teaching_apprenticeship: true
    provider_led_undergrad: true
    opt_in_undergrad: true

pagination:
  records_per_page: 30

environment:
  name: development

track_validation_errors: false

blazer_database_url: postgresql://localhost/register_trainee_teacher_data_development
