# The url for this app, also used by `dfe_sign_in`
base_url: https://pen.register-trainee-teachers.service.gov.uk

trs:
  base_url: https://preprod.teacher-qualifications-api.education.gov.uk/

dfe_sign_in:
  # URL that the users are redirected to for signing in
  issuer: https://pp-oidc.signin.education.gov.uk
  # URL of the users profile
  profile: https://pp-profile.signin.education.gov.uk

recruits_api:
  base_url: "https://sandbox.apply-for-teacher-training.service.gov.uk/register-api"

features:
  basic_auth: false
  sign_in_method: dfe-sign-in
  enable_feedback_link: false
  import_courses_from_ttapi: true
  import_applications_from_apply: true
  publish_course_details: true
  integrate_with_trs: false
  google:
    send_data_to_big_query: false

environment:
  name: pen
  display_name: Pen Test

google:
  big_query:
    entity_table_checks_enabled: false
