# The url for this app, also used by `dfe_sign_in`
base_url: https://www.register-trainee-teachers.education.gov.uk

# The url for the google doc feedback link (live version)
feedback_link_url: "https://docs.google.com/forms/d/e/1FAIpQLScTW00rH5Gm8Ama38fgGNQ6Ek7CQPRyadjBfp3BvhYkwJS1jw/viewform"

# The url for the google doc feedback link for recommended for award (live version)
recommended_for_award_feedback_url: "https://docs.google.com/forms/d/e/1FAIpQLScqCdDNyDHNBuUDG5YGWL7TzFI2WdmL6ib5326tUsphtC7PfQ/viewform"

# The url for the google doc feedback link for submitting a trainee for trn (live version)
trn_submitted_feedback_url: "https://docs.google.com/forms/d/e/1FAIpQLSd-Jc3ef8yNYmIps3H905TuUkVfLYqpwP5ouQilNbHMSElCkg/viewform"

dttp:
  back_office_url: https://dttp.crm4.dynamics.com/
  scope: https://dttp.crm4.dynamics.com/.default
  api_base_url: https://dttp.crm4.dynamics.com/api/data/v9.1

dfe_sign_in:
  # URL that the users are redirected to for signing in
  issuer: https://oidc.signin.education.gov.uk
  # URL of the users profile
  profile: https://profile.signin.education.gov.uk

features:
  basic_auth: false
  enable_feedback_link: true
  sync_from_dttp: true
  send_emails: true
  run_consistency_check_job: true
  persist_to_dttp: true

environment:
  name: beta
