# The url for this app, also used by `dfe_sign_in`
base_url: https://qa.register-trainee-teachers.education.gov.uk

dttp:
  back_office_url: https://dttp-test.crm4.dynamics.com/
  scope: https://dttp-test.crm4.dynamics.com/.default
  api_base_url: https://dttp-test.crm4.dynamics.com/api/data/v9.1

features:
  home_text: true
  use_dfe_sign_in: false
  import_courses_from_ttapi: true
  publish_course_details: true
  imported_from_apply_filter: true
  course_study_mode: true
  routes:
    provider_led_postgrad: true
    provider_led_undergrad: true
    early_years_assessment_only: true
    early_years_postgrad: true
    early_years_salaried: true
    school_direct_salaried: true
    school_direct_tuition_fee: true
    pg_teaching_apprenticeship: true

pagination:
  records_per_page: 30
