# The url for the google doc feedback link (non-live version)
feedback_link_url: "https://docs.google.com/forms/d/e/1FAIpQLSdYg4IA2tMiSfqIjM9CslVgFzsSazznD6VoT41g19sJYCwsLQ/viewform"

# The url for this app, also used by `dfe_sign_in`
base_url: https://qa.register-trainee-teachers.education.gov.uk

dttp:
  back_office_url: https://dttp-test.crm4.dynamics.com/
  scope: https://dttp-test.crm4.dynamics.com/.default
  api_base_url: https://dttp-test.crm4.dynamics.com/api/data/v9.1

features:
  home_text: true
  use_dfe_sign_in: false
  routes_provider_led_postgrad: true
  routes_early_years_undergrad: true

pagination:
  records_per_page: 30
