# The url for this app, also used by `dfe_sign_in`
base_url: https://qa.register-trainee-teachers.service.gov.uk

dttp:
  scope: https://dttp-test.crm4.dynamics.com/.default
  api_base_url: https://dttp-test.crm4.dynamics.com/api/data/v9.1
  portal_host: traineeteacherportal-dv.education.gov.uk

dqt:
  base_url: https://test.teacher-qualifications-api.education.gov.uk/

trs:
  base_url: https://test.teacher-qualifications-api.education.gov.uk/

features:
  home_text: true
  sign_in_method: persona
  import_courses_from_ttapi: true
  publish_course_details: true
  course_study_mode: true
  routes:
    provider_led_postgrad: true
    provider_led_undergrad: true
    assessment_only: true
    early_years_assessment_only: true
    early_years_postgrad: true
    early_years_salaried: true
    early_years_undergrad: true
    school_direct_salaried: true
    school_direct_tuition_fee: true
    pg_teaching_apprenticeship: true
    opt_in_undergrad: true
    iqts: true
    teacher_degree_apprenticeship: true
  google:
    send_data_to_big_query: true

pagination:
  records_per_page: 30
