# The url for the google doc feedback link (non-live version)
feedback_link_url: "https://docs.google.com/forms/d/e/1FAIpQLSdYg4IA2tMiSfqIjM9CslVgFzsSazznD6VoT41g19sJYCwsLQ/viewform"

features:
  home_text: true
  use_dfe_sign_in: false
  enable_feedback_link: true
  routes_provider_led_postgrad: true
  routes_early_years_undergrad: true

pagination:
  records_per_page: 30

environment:
  name: review
