dqt:
  base_url: https://test.teacher-qualifications-api.education.gov.uk/

trs:
  base_url: https://test.teacher-qualifications-api.education.gov.uk/

features:
  home_text: true
  sign_in_method: persona
  enable_feedback_link: true
  publish_course_details: true
  token_management: true
  routes:
    provider_led_postgrad: true
    assessment_only: true
    early_years_assessment_only: true
    early_years_salaried: true
    early_years_postgrad: true
    early_years_undergrad: true
    school_direct_salaried: true
    school_direct_tuition_fee: true
    pg_teaching_apprenticeship: true
    provider_led_undergrad: true
    opt_in_undergrad: true
    iqts: true
    teacher_degree_apprenticeship: true
  user_can_have_multiple_organisations: true
  funding: true
  google:
    send_data_to_big_query: true
pagination:
  records_per_page: 30

environment:
  name: review
  display_name: Review
