dqt:
  base_url: https://test.teacher-qualifications-api.education.gov.uk/

trs:
  base_url: https://test.teacher-qualifications-api.education.gov.uk/

features:
  home_text: true
  sign_in_method: persona
  enable_feedback_link: true
  publish_course_details: true
  user_can_have_multiple_organisations: true
  funding: true
  google:
    send_data_to_big_query: true

pagination:
  records_per_page: 30

environment:
  name: review
  display_name: Review

sign_off_period: census_period

api:
  allowed_versions: [v2025.0-rc, v2025.0, v2026.0]
