features:
  home_text: true
  use_dfe_sign_in: false
  enable_feedback_link: true
  publish_course_details: true
  show_funding: true
  persist_to_dttp: false
  imported_from_apply_filter: true
  course_study_mode: true
  enable_teach_first_provider: true
  routes:
    provider_led_postgrad: true
    early_years_assessment_only: true
    early_years_postgrad: true
    school_direct_salaried: true
    school_direct_tuition_fee: true
    pg_teaching_apprenticeship: true

pagination:
  records_per_page: 30

environment:
  name: review
