features:
  home_text: true
  use_dfe_sign_in: false
  enable_feedback_link: true
  routes:
    provider_led_postgrad: true
    early_years_undergrad: true
    school_direct_salaried: true
    school_direct_tuition_fee: true

pagination:
  records_per_page: 30

environment:
  name: review
