dqt:
  base_url: https://test-teacher-qualifications-api.education.gov.uk/

features:
  home_text: true
  use_dfe_sign_in: false
  enable_feedback_link: true
  publish_course_details: true
  persist_to_dttp: false
  routes:
    provider_led_postgrad: true
    early_years_assessment_only: true
    early_years_salaried: true
    early_years_postgrad: true
    early_years_undergrad: true
    school_direct_salaried: true
    school_direct_tuition_fee: true
    pg_teaching_apprenticeship: true
    provider_led_undergrad: true
    opt_in_undergrad: true
  user_can_have_multiple_organisations: true
  integrate_with_dqt: true

pagination:
  records_per_page: 30

environment:
  name: review

dqt:
  base_url: "https://test-teacher-qualifications-api.education.gov.uk/"
