# The url for this app, also used by `dfe_sign_in`
base_url: https://sandbox.register-trainee-teachers.education.gov.uk

dttp:
  back_office_url: https://dttp.crm4.dynamics.com/
  scope: https://dttp.crm4.dynamics.com/.default
  api_base_url: https://dttp.crm4.dynamics.com/api/data/v9.1

dfe_sign_in:
  # URL that the users are redirected to for signing in
  issuer: https://oidc.signin.education.gov.uk
  # URL of the users profile
  profile: https://profile.signin.education.gov.uk

features:
  basic_auth: false
