dttp:
  api_base_url: "https://test-api-base-uri.com"
  portal_host: traineeteacherportal-test.education.gov.uk

slack:
  default_channel: "test-channel"
  webhook_url: "https://test-slack-webhook-url.com"
features:
  sign_in_method: dfe
  basic_auth: false
  routes:
    school_direct_salaried: true
    school_direct_tuition_fee: true
    pg_teaching_apprenticeship: true
  redirect_education_domain: true

environment:
  name: beta

trainee_export:
  record_limit: 100

govuk_notify:
  api_key: please_change_me
  welcome_email_template_id: test-uuid
  otp_email_template_id: test-uuid
