name: build

on:
  push:
   branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: dfedigital/register-trainee-teachers
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOSTNAME: localhost

    steps:
    - uses: actions/checkout@v2
      name: Checkout

    - name: Set environment variables
      run: |
        GIT_SHA_SHORT=$(echo ${GITHUB_SHA} | cut -c 1-7)
        echo "GIT_SHA_SHORT=$GIT_SHA_SHORT" >> $GITHUB_ENV
        echo "SHA_TAG=$GIT_SHA_SHORT" >> $GITHUB_ENV

    - name: Login to DockerHub
      if: github.actor != 'dependabot[bot]'
      uses: docker/login-action@v1.9.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PERSONAL_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1.3.0

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        tags: ${{env.DOCKER_REPO}}:${{env.SHA_TAG}}
        builder: ${{ steps.buildx.outputs.name }}
        load: true
        cache-to: type=inline
        cache-from: | 
          type=registry,ref=${{env.DOCKER_REPO}}:master
          type=registry,ref=${{env.DOCKER_REPO}}:${{env.SHA_TAG}}
        build-args: COMMIT_SHA=${{ github.sha }}

    - name: Trigger Review App Deployment
      if: ${{ success() && github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' }}
      uses: benc-uk/workflow-dispatch@v1.1
      with:
        workflow: 'Deploy to PaaS'
        ref: ${{ github.head_ref }}
        token: ${{ secrets.API_TOKEN_FOR_GITHUB_ACTION }}
        inputs: '{"pr": "${{ github.event.pull_request.number }}", "sha": "${{ env.SHA_TAG }}"}'

    - name: Bring images up
      run: |
        docker-compose up --no-build -d
        docker-compose exec -T web /bin/sh -c "./wait-for-command.sh -c 'nc -z db 5432' -s 0 -t 20"
        docker-compose exec -T web /bin/sh -c "yarn add jest"

    - name: Install chromedriver
      run: docker-compose exec -T web /bin/sh -c 'apk add chromium chromium-chromedriver'

    - name: Setup DB
      run: docker-compose exec -T web /bin/sh -c "bundle exec rails db:setup"

    - name: Run Ruby Linter
      run: docker-compose exec -T web /bin/sh -c 'bundle exec rubocop app config db lib spec Gemfile --format clang'

    - name: Run JavaScript Linter
      run: docker-compose exec -T web /bin/sh -c 'bundle exec rake lint:javascript'

    - name: Run SCSS Linter
      run:  docker-compose exec -T web /bin/sh -c 'bundle exec rake lint:scss'

    - name: Run Rspec tests
      run: docker-compose exec --env COVERAGE=true -T web /bin/sh -c 'bundle exec rake spec'

    - name: Run Javascript tests
      run: docker-compose exec -T web /bin/sh -c 'yarn run test'

    - name: Tag master image
      if: github.ref == 'refs/heads/master'
      run: docker tag ${{env.DOCKER_REPO}}:${{env.SHA_TAG}} ${{env.DOCKER_REPO}}:master

    - name: Push Docker Image
      if: github.actor != 'dependabot[bot]'
      run: |
        docker push ${{env.DOCKER_REPO}}:${{env.SHA_TAG}} 
        docker push ${{env.DOCKER_REPO}}:master || true

    - name: Trigger QA Deployment
      if: ${{ success() && github.ref == 'refs/heads/master' }}
      uses: benc-uk/workflow-dispatch@v1.1
      with:
        workflow: 'Deploy to PaaS'
        token: ${{ secrets.API_TOKEN_FOR_GITHUB_ACTION }}
        inputs: '{"qa": "true", "staging": "true", "production": "true", "sandbox": "true", "rollover": "true", "sha": "${{ env.SHA_TAG }}"}'

    - name: Check for Failure
      if: ${{ failure() && github.ref == 'refs/heads/master' }}
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: twd_publish_register_tech
        SLACK_COLOR: '#ef5343'
        SLACK_ICON_EMOJI: ':github-logo:'
        SLACK_USERNAME: Register Trainee Teachers
        SLACK_TITLE: Build Failure
        SLACK_MESSAGE: ':alert: Build failure on ${{ github.event.inputs.environment }} :sadparrot:'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
